export const COURSES_LIST_REQUEST = "COURSES_LIST_REQUEST";
export const COURSES_LIST_SUCCESS = "COURSES_LIST_SUCCESS";
export const COURSES_LIST_FAIL = "COURSES_LIST_FAIL";

export const COURSES_DETAILS_REQUEST = "COURSES_DETAILS_REQUEST";
export const COURSES_DETAILS_SUCCESS = "COURSES_DETAILS_SUCCESS";
export const COURSES_DETAILS_FAIL = "COURSES_DETAILS_FAIL";

export const UPDATE_COURSES_DETAILS_REQUEST = "UPDATE_COURSES_DETAILS_REQUEST";
export const UPDATE_COURSES_DETAILS_SUCCESS = "UPDATE_COURSES_DETAILS_SUCCESS";
export const UPDATE_COURSES_DETAILS_FAIL = "UPDATE_COURSES_DETAILS_FAIL";

export const CREATE_COURSES_REQUEST = "CREATE_COURSES_REQUEST";
export const CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS";
export const CREATE_COURSES_FAIL = "CREATE_COURSES_FAIL";
export const CREATE_COURSES_RESET = "CREATE_COURSES_RESET";

export const COURSE_REMOVE_REQUEST = "COURSE_REMOVE_REQUEST";
export const COURSE_REMOVE_SUCCESS = "COURSE_REMOVE_SUCCESS";
export const COURSE_REMOVE_FAIL = "COURSE_REMOVE_FAIL";
