export const ENROLLMENT_LIST_REQUEST = "ENROLLMENT_LIST_REQUEST";
export const ENROLLMENT_LIST_SUCCESS = "ENROLLMENT_LIST_SUCCESS";
export const ENROLLMENT_LIST_FAIL = "ENROLLMENT_LIST_FAIL";

export const ENROLLMENT_DETAILS_REQUEST = "ENROLLMENT_DETAILS_REQUEST";
export const ENROLLMENT_DETAILS_SUCCESS = "ENROLLMENT_DETAILS_SUCCESS";
export const ENROLLMENT_DETAILS_FAIL = "ENROLLMENT_DETAILS_FAIL";

export const UPDATE_ENROLLMENT_DETAILS_REQUEST = "UPDATE_ENROLLMENT_DETAILS_REQUEST";
export const UPDATE_ENROLLMENT_DETAILS_SUCCESS = "UPDATE_ENROLLMENT_DETAILS_SUCCESS";
export const UPDATE_ENROLLMENT_DETAILS_FAIL = "UPDATE_ENROLLMENT_DETAILS_FAIL";

export const CREATE_ENROLLMENT_REQUEST = "CREATE_ENROLLMENT_REQUEST";
export const CREATE_ENROLLMENT_SUCCESS = "CREATE_ENROLLMENT_SUCCESS";
export const CREATE_ENROLLMENT_FAIL = "CREATE_ENROLLMENT_FAIL";
export const CREATE_ENROLLMENT_RESET = "CREATE_ENROLLMENT_RESET";

export const ENROLLMENT_REMOVE_REQUEST = "ENROLLMENT_REMOVE_REQUEST";
export const ENROLLMENT_REMOVE_SUCCESS = "ENROLLMENT_REMOVE_SUCCESS";
export const ENROLLMENT_REMOVE_FAIL = "ENROLLMENT_REMOVE_FAIL";
