export const STUDENT_LIST_REQUEST = "STUDENT_LIST_REQUEST";
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS";
export const STUDENT_LIST_FAIL = "STUDENT_LIST_FAIL";

export const STUDENT_DETAILS_REQUEST = "STUDENT_DETAILS_REQUEST";
export const STUDENT_DETAILS_SUCCESS = "STUDENT_DETAILS_SUCCESS";
export const STUDENT_DETAILS_FAIL = "STUDENT_DETAILS_FAIL";

export const UPDATE_STUDENT_DETAILS_REQUEST = "UPDATE_STUDENT_DETAILS_REQUEST";
export const UPDATE_STUDENT_DETAILS_SUCCESS = "UPDATE_STUDENT_DETAILS_SUCCESS";
export const UPDATE_STUDENT_DETAILS_FAIL = "UPDATE_STUDENT_DETAILS_FAIL";

export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAIL = "CREATE_STUDENT_FAIL";
export const CREATE_STUDENT_RESET = "CREATE_STUDENT_RESET";

export const STUDENT_REMOVE_REQUEST = "STUDENT_REMOVE_REQUEST";
export const STUDENT_REMOVE_SUCCESS = "STUDENT_REMOVE_SUCCESS";
export const STUDENT_REMOVE_FAIL = "STUDENT_REMOVE_FAIL";
